USE [master]
GO

/****** Object:  Database [cci10timesteps]    Script Date: 11/22/2016 2:05:25 PM ******/
DROP DATABASE [cci10timesteps]
GO

/****** Object:  Database [cci10timesteps]    Script Date: 11/22/2016 2:05:25 PM ******/
CREATE DATABASE [cci10timesteps]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'PRIMARY', FILENAME = N'C:\data\data5\sql_db\cci10timesteps_PRIMARY.mdf' , SIZE = 24576KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB ), 
 FILEGROUP [FG01] 
( NAME = N'turbdb101_FG01', FILENAME = N'C:\data\data5\sql_db\cci10timesteps_FG01.ndf' , SIZE = 2097152KB , MAXSIZE = UNLIMITED, FILEGROWTH = 51200KB ), 
 FILEGROUP [FG02] 
( NAME = N'turbdb101_FG02', FILENAME = N'C:\data\data6\sql_db\cci10timesteps_FG02.ndf' , SIZE = 2097152KB , MAXSIZE = UNLIMITED, FILEGROWTH = 51200KB ), 
 FILEGROUP [FG03] 
( NAME = N'turbdb101_FG03', FILENAME = N'C:\data\data7\sql_db\cci10timesteps_FG03.ndf' , SIZE = 2097152KB , MAXSIZE = UNLIMITED, FILEGROWTH = 51200KB ), 
 FILEGROUP [FG04] 
( NAME = N'turbdb101_FG04', FILENAME = N'C:\data\data8\sql_db\cci10timesteps_FG04.ndf' , SIZE = 2097152KB , MAXSIZE = UNLIMITED, FILEGROWTH = 51200KB ), 
 FILEGROUP [FG05] 
( NAME = N'turbdb101_FG05', FILENAME = N'C:\data\data5\sql_db\cci10timesteps_FG05.ndf' , SIZE = 2097152KB , MAXSIZE = UNLIMITED, FILEGROWTH = 51200KB ), 
 FILEGROUP [FG06] 
( NAME = N'turbdb101_FG06', FILENAME = N'C:\data\data6\sql_db\cci10timesteps_FG06.ndf' , SIZE = 2097152KB , MAXSIZE = UNLIMITED, FILEGROWTH = 51200KB ), 
 FILEGROUP [FG07] 
( NAME = N'turbdb101_FG07', FILENAME = N'C:\data\data7\sql_db\cci10timesteps_FG07.ndf' , SIZE = 2097152KB , MAXSIZE = UNLIMITED, FILEGROWTH = 51200KB ), 
 FILEGROUP [FG08] 
( NAME = N'turbdb101_FG08', FILENAME = N'C:\data\data8\sql_db\cci10timesteps_FG08.ndf' , SIZE = 2097152KB , MAXSIZE = UNLIMITED, FILEGROWTH = 51200KB ), 
 FILEGROUP [FG09] 
( NAME = N'turbdb101_FG09', FILENAME = N'C:\data\data5\sql_db\cci10timesteps_FG09.ndf' , SIZE = 2097152KB , MAXSIZE = UNLIMITED, FILEGROWTH = 51200KB ), 
 FILEGROUP [FG10] 
( NAME = N'turbdb101_FG10', FILENAME = N'C:\data\data6\sql_db\cci10timesteps_FG10.ndf' , SIZE = 2097152KB , MAXSIZE = UNLIMITED, FILEGROWTH = 51200KB ), 
 FILEGROUP [FG11] 
( NAME = N'turbdb101_FG11', FILENAME = N'C:\data\data7\sql_db\cci10timesteps_FG11.ndf' , SIZE = 2097152KB , MAXSIZE = UNLIMITED, FILEGROWTH = 51200KB ), 
 FILEGROUP [FG12] 
( NAME = N'turbdb101_FG12', FILENAME = N'C:\data\data8\sql_db\cci10timesteps_FG12.ndf' , SIZE = 2097152KB , MAXSIZE = UNLIMITED, FILEGROWTH = 51200KB ), 
 FILEGROUP [FG13] 
( NAME = N'turbdb101_FG13', FILENAME = N'C:\data\data5\sql_db\cci10timesteps_FG13.ndf' , SIZE = 2097152KB , MAXSIZE = UNLIMITED, FILEGROWTH = 51200KB ), 
 FILEGROUP [FG14] 
( NAME = N'turbdb101_FG14', FILENAME = N'C:\data\data6\sql_db\cci10timesteps_FG14.ndf' , SIZE = 2097152KB , MAXSIZE = UNLIMITED, FILEGROWTH = 51200KB ), 
 FILEGROUP [FG15] 
( NAME = N'turbdb101_FG15', FILENAME = N'C:\data\data7\sql_db\cci10timesteps_FG15.ndf' , SIZE = 2097152KB , MAXSIZE = UNLIMITED, FILEGROWTH = 51200KB ), 
 FILEGROUP [FG16] 
( NAME = N'turbdb101_FG16', FILENAME = N'C:\data\data8\sql_db\cci10timesteps_FG16.ndf' , SIZE = 2097152KB , MAXSIZE = UNLIMITED, FILEGROWTH = 51200KB )
 LOG ON 
( NAME = N'turbdb101_log', FILENAME = N'C:\data\data9\sql_db\cci10timesteps_log.ldf' , SIZE = 19393856KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO



IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [cci10timesteps].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [cci10timesteps] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [cci10timesteps] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [cci10timesteps] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [cci10timesteps] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [cci10timesteps] SET ARITHABORT OFF 
GO

ALTER DATABASE [cci10timesteps] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [cci10timesteps] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [cci10timesteps] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [cci10timesteps] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [cci10timesteps] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [cci10timesteps] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [cci10timesteps] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [cci10timesteps] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [cci10timesteps] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [cci10timesteps] SET  DISABLE_BROKER 
GO

ALTER DATABASE [cci10timesteps] SET AUTO_UPDATE_STATISTICS_ASYNC ON 
GO

ALTER DATABASE [cci10timesteps] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [cci10timesteps] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [cci10timesteps] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO

ALTER DATABASE [cci10timesteps] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [cci10timesteps] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [cci10timesteps] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [cci10timesteps] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [cci10timesteps] SET  MULTI_USER 
GO

ALTER DATABASE [cci10timesteps] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [cci10timesteps] SET DB_CHAINING OFF 
GO

ALTER DATABASE [cci10timesteps] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [cci10timesteps] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [cci10timesteps] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [cci10timesteps] SET  READ_WRITE 
GO


